controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    effort_controllers:
      type: effort_controllers/JointGroupEffortController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

effort_controllers:
  ros__parameters:
    joints:
      - joint_base_1
      - joint_12
      - joint_23
      - joint_34
      - joint_45
      - joint_56
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
      - effort
    open_loop_control: true
